### ISSUE TITLE
您好，运行出错。

### ISSUE THREAD

**Issue by Kingsleyooo** [Shapooo/weiback-rs#1]
程序崩了，原因: TypeError: Cannot read properties of null (reading 'avatar_hd')

**Comment by Shapooo** [comment]
> 程序崩了，原因: TypeError: Cannot read properties of null (reading 'avatar_hd')

不好意思，刚看到 Issue。
两周前代码还完全没有稳定，到现在代码已经发生了非常大的变动。请问现在还有同样的问题吗？
