### ISSUE TITLE
会支持mac吗

### ISSUE THREAD

**Issue by linzzzzllll** [Shapooo/weiback-rs#4]
会支持mac吗

**Comment by Shapooo** [comment]
代码中并没有使用不支持 Mac 的库或特性。所以如果在 Mac 上自行编译应该是可以使用的。
但是因为我没有 Mac 设备，所以出现平台相关的问题时我是没有办法解决的，我也就没有在 Release 中添加 Mac。
如果有需求我可以在后续 Release 中添加 Mac，只是平台相关的 Bug 我不会负责。
